# Generated by Django 3.2.3 on 2024-05-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitate', models.CharField(max_length=150, verbose_name='Localitate')),
                ('judet', models.CharField(max_length=150, verbose_name='Judet')),
                ('tara', models.CharField(max_length=150, verbose_name='Tara')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=50, verbose_name='Titlu Categorie')),
                ('slug', models.SlugField(max_length=55, verbose_name='Categorie Slug')),
                ('descriere', models.TextField(blank=True, verbose_name='Descriere Categorie')),
                ('categorie_imagine', models.ImageField(blank=True, null=True, upload_to='categorie', verbose_name='Categorie Imagine')),
                ('este_activ', models.BooleanField(verbose_name='Este Activ?')),
                ('recomandat', models.BooleanField(verbose_name='Este Recomandat?')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data crearii')),
                ('reinoit', models.DateTimeField(auto_now=True, verbose_name='Data reinoarii')),
            ],
            options={
                'verbose_name_plural': 'Categorii',
                'ordering': ('-create',),
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(verbose_name='Cantitate')),
                ('data_comenzii', models.DateTimeField(auto_now_add=True, verbose_name='Data Comenzii')),
                ('status', models.CharField(choices=[('In asteptare', 'In asteptare'), ('Acceptat', 'Acceptat'), ('Impachetat', 'Impachetat'), ('Urmeaza livrarea', 'Urmeaza livrarea'), ('Livrat', 'Livrat'), ('Anulat', 'Anulat')], default='In asteptare', max_length=50)),
                ('adresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.adresa', verbose_name='Adresa livrarii')),
            ],
        ),
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.PositiveIntegerField(default=1, verbose_name='Cantitate')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data crearii')),
                ('reinoit', models.DateTimeField(auto_now=True, verbose_name='Data reinoarii')),
            ],
        ),
        migrations.CreateModel(
            name='MarimeProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marime', models.CharField(max_length=50, verbose_name='Marime Produs')),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=250, verbose_name='Titlu Produs')),
                ('slug', models.SlugField(max_length=160, verbose_name='Product Slug')),
                ('sku', models.CharField(max_length=255, unique=True, verbose_name='Unique Product ID (SKU)')),
                ('descriere', models.TextField(verbose_name='Descriere')),
                ('detalii', models.TextField(blank=True, null=True, verbose_name='Detalii')),
                ('imagine_produs', models.ImageField(blank=True, null=True, upload_to='produs', verbose_name='Imagine Produs')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marime', models.CharField(blank=True, max_length=50, null=True, verbose_name='Marime Produs')),
                ('este_activ', models.BooleanField(verbose_name='Este Activ?')),
                ('recomandat', models.BooleanField(verbose_name='Este Recomandat?')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Data crearii')),
                ('reinoit', models.DateTimeField(auto_now=True, verbose_name='Data reinoarii')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.categorie', verbose_name='Categorie Produs')),
            ],
            options={
                'verbose_name_plural': 'Produse',
                'ordering': ('-create',),
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.AddField(
            model_name='marimeprodus',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marimi', to='store.produs'),
        ),
        migrations.AddField(
            model_name='cos',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produs', verbose_name='Produs'),
        ),
        migrations.AddField(
            model_name='cos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='produs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.produs', verbose_name='Produs'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
