# Generated by Django 3.2.3 on 2024-05-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20240531_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='este_activ',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='recomandat',
        ),
        migrations.RemoveField(
            model_name='produs',
            name='este_activ',
        ),
        migrations.RemoveField(
            model_name='produs',
            name='recomandat',
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Is Featured?'),
        ),
        migrations.AddField(
            model_name='produs',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
        migrations.AddField(
            model_name='produs',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='Is Featured?'),
        ),
    ]
