# Generated by Django 5.0.6 on 2024-06-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240531_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
