# Generated by Django 5.0.6 on 2024-06-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
